EHYSSE Noussiratou
dehboris/trombi-g1-2024 pull request #9
Opened 2024-12-07 18:28 UTC by KemiEhysse

Ajout de mes informations personnelles au tableau HTML

2024-12-07 22:26 UTC, Florent242 commented
Nom + prénoms uniquement
Pour le titre du pull request

2024-12-07 22:40 UTC, Florent242 approved these changes

2024-12-07 22:48 UTC, Florent242 commented
Faire une mise a jour du dépot.

2024-12-07 22:50 UTC, Florent242 requested changes
Doit faire une mise a jour du depot, car ancienne version du depot

2024-12-08 01:41 UTC, merged

2024-12-08 01:54 UTC, dehboris commented
Apres la mise à jour du dépôt, il faut également corriger correctement la numérotation